### ISSUE TITLE
Return null instead of throwing java.lang.IllegalStateException while calling getX on empty point.

### ISSUE THREAD

**Issue by sp-suresh** [simplegeo/jts#1]
I am using geomesa accumulo with vividsolution to operate on Point geometry types. However, while storing null for geometry point method getX() throws exception of calling getX on empty point. Here is my Log
```

java.lang.IllegalStateException: getX called on empty Point
	at com.vividsolutions.jts.geom.Point.getX(Point.java:124)
	at org.locationtech.geomesa.utils.uuid.Z3UuidGenerator$.createUuid(Z3FeatureIdGenerator.scala:93)
	at org.locationtech.geomesa.utils.uuid.Z3UuidGenerator$.createUuid(Z3FeatureIdGenerator.scala:70)
	at org.locationtech.geomesa.utils.uuid.Z3FeatureIdGenerator.createId(Z3FeatureIdGenerator.scala:32)
	at org.locationtech.geomesa.index.geotools.GeoMesaFeatureWriter$.featureWithFid(GeoMesaFeatureWriter.scala:64)
	at org.locationtech.geomesa.index.geotools.GeoMesaFeatureWriter.writeFeature(GeoMesaFeatureWriter.scala:128)
	at org.locationtech.geomesa.index.geotools.GeoMesaAppendFeatureWriter$class.write(GeoMesaFeatureWriter.scala:194)
	at org.locationtech.geomesa.accumulo.data.AccumuloAppendFeatureWriter.write(AccumuloFeatureWriter.scala:19)
	at com.hps.GeomesaClient.insert(GeomesaClient.java:129)
```

**Comment by sp-suresh** [comment]
Closing this issue as it seems that function createUuid of geomesa needs an empty check and issue is not with jts
